### ISSUE TITLE
how to run it ?

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5-web#15]
hello there,
how do i actually install and run it,
os ot possible to know if this is able to run on a network without internet connection. ?

**Comment by larshp** [comment]
you can try it out at https://abap2ui5.github.io/web-abap2ui5-samples/

if you want to run it locally, install NodeJS 20, clone the repository and do

```
npm run clone
npm run unit
npm run express
```

**Comment by choper725** [comment]
thanks @larshp 

regaring the other question, do you think its possible ? if do, any idea how its could bw done

**Comment by larshp** [comment]
without network connection? yea, it will run, just need to download the files somehow

**Comment by choper725** [comment]
files means all the dependencies ?

**Comment by larshp** [comment]
yea

**Comment by oblomov-dev** [comment]
i guess this can be closed
