### ISSUE TITLE
trying to run on windows

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5-web#4]
hi @larshp 
does it suppose to work on windows also ??
seems to get errors on running npm test.. on linux commands.. rm & cp ..

do i need to do something in order to get it to work ??

**Comment by larshp** [comment]
try using bash, its typically part of the git installation

![image](https://github.com/larshp/abap2ui5-web/assets/5888506/73b93a59-e321-423b-8f78-92dedc495214)
